### ISSUE TITLE
Investigate 'unable to connect' error.

### ISSUE THREAD

**Issue by kjpc-tech** [kjpc-tech/MONITor#1]
Review states getting 'unable to connect' error. Port and credentials should be ok. Maybe a self-signed ssl certificate issue?

**Comment by Novae7** [comment]
Server is Monit 5.9
Password Contains "#"

so, what should I test? ;)

**Comment by kjpc-tech** [comment]
I think it's the SSL certificate like you suggested. I was able to replicate the `Error: unable to connect.` when pointing to a self-signed certificate on https://badssl.com/. When ignoring SSL (added on the [beta branch](https://github.com/kjpc-tech/MONITor/tree/beta)), I get the error `Error: dashboard not visible.` which is expected because the badssl page is not Monit.

I've released an update on [Google Play](https://play.google.com/store/apps/details?id=tech.kjpc.monitorapp) available to beta testers (may take awhile before it's active). The release notes will say 'Added setting to trust all SSL certificates.' If you're willing, please download it and see if it works!

**Comment by Novae7** [comment]
Works for me :)
"Success: can connect"

But when i tap the Name i just get "Monit Interface" with a blank site?

**Comment by kjpc-tech** [comment]
Whoops I forgot about that part of the app. The 'ignore ssl' setting applies on the webview as well now. Just pushed an update for beta testers (again, may take awhile before it's active). Is it working now?

**Comment by Novae7** [comment]
Works now :)

thanks a lot!

**Comment by kjpc-tech** [comment]
Awesome. Thank you for testing!

**Comment by kjpc-tech** [comment]
Fixed with #2.
