### ISSUE TITLE
App crashes often on Lineageos 15.1 while in the background

### ISSUE THREAD

**Issue by e-alfred** [kjpc-tech/MONITor#5]
Hello,

I have MONITor installed on Lineageos 15.1 and it crashes from time to time while in the background. It simply shows a message "MONITor crashed" and lets me send some feedback to the developer. You should have received several detailed messages using the feedback option of the Google Crash reporter that I sent you.

**Comment by kjpc-tech** [comment]
Thanks for reporting this. I'm investigating.

**Comment by kjpc-tech** [comment]
Appears to be related to [th](https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten)e[se](https://stackoverflow.com/questions/44502229/runtime-exception-android-o-with-boot-completed). I'll work on a fix.

**Comment by kjpc-tech** [comment]
Thanks for reporting @e-alfred. Please reopen if you're having the same problem.

**Comment by e-alfred** [comment]
Thanks, this works well now. But on Android 9/Lineageos 16.0 there is now another problem regarding running Monit on http instead of https and MONITor showing "Unable to connect" and "net::ERR_CLEARTEXT_NOT_PERMITTED" if I try to access the website.
